version: '2'
services:
  droid_base:
    container_name: droid_base
    image: postgres:13
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=AIdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    labels:
      - "traefik.enable=false"
  droid_app:
    container_name: droid_app
    build: ./app
    restart: always
    environment:
      - PORT=5000
      - DB_NAME=AIdata
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=droid_base
      - DB_PORT=5432
    depends_on:
      - droid_base
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.droid.rule=Host(`droidback.it-apostol.ru`)"
      - "traefik.http.routers.droid.entrypoints=http"
      - "traefik.http.routers.droid.service=droid_app"
      - "traefik.http.services.droid_app.loadbalancer.server.port=5000"